name: Releases

on:
  workflow_dispatch:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          tag: "sss"
          artifacts: "release.tar.gz,main/*.exe"
#          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}